version: '3.4'

services:
    db:
        image: redis:6.0
        ports:
            - 6379:6379

    api:
        build:
            context: ./
            dockerfile: ./Dockerfile.api
        ports:
            - 8080:8080
        depends_on: ['db']